version: "3.9"

services:
  database:
    image: postgres
    container_name: postgres
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "greenlight"
      POSTGRES_PASSWORD: "pa55word"
      POSTGRES_DB: "greenlight"
    restart: always


volumes:
  database: