basePath: /v1
definitions:
  main.Input:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    name: Jessica Tarra
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Greenlight API Docs
  version: 1.0.0
paths:
  /movies:
    get:
      consumes:
      - application/json
      description: Fetch movies with server pagination
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Fetch list of with server pagination
      tags:
      - movies
  /users:
    post:
      consumes:
      - application/json
      description: Registers a new user.
      parameters:
      - description: User registration data
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/main.Input'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Register User
      tags:
      - users
  /users/activate:
    put:
      consumes:
      - application/json
      description: Activates a user account using a token.
      parameters:
      - description: Token for user activation
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Activate User
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
