name: Fly Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  audit:
    uses: ./.github/workflows/audit.yaml
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: echo "API_VERSION=$(git describe --always --dirty --tags --long)"
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SMTP_HOST: ${{ env.SMTP_HOST }}
          SMTP_PORT: ${{ env.SMTP_PORT }}
          SMTP_USERNAME: ${{ env.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ env.SMTP_SENDER }}
          CORS_TRUSTED_ORIGINS: ${{ env.CORS_TRUSTED_ORIGINS }}
          API_PORT: ${{ env.API_PORT }}
          API_ENV: ${{ env.API_ENV }}